// Real PageContent JSON data extracted from mock CMS files
// All image imports converted to /images/ URL paths

export const pageContentData: Record<string, object> = {
    homepage: {
        hero_bento: {
            badge: "Spesialis Tanaman Hias Langka",
            heading: "Bumi Mekarsari Jaya",
            description: "Koleksi Anthurium, Monstera, dan Philodendron langka. Agregator petani Cipanas—kualitas unggul, pengiriman terpercaya.",
            backgroundImage: "/images/pages/nursery-main.webp",
            trendingTags: ["Variegated", "Large Form", "Rare Aroids"],
            ctaPrimaryLabel: "Jelajahi Koleksi",
            ctaPrimaryHref: "/product",
            ctaSecondaryLabel: "Untuk Bisnis/Grosir",
            ctaSecondaryHref: "/layanan",
            featuredPlantName: "Bonsai Juniper",
            featuredPlantPrice: "IDR 2.5jt",
            featuredPlantImage: "/images/products/bonsai-2.webp",
            featuredPlantHref: "/product",
        },
        trust_strip: {
            pills: [
                { id: "1", icon: "local_shipping", label: "Pengiriman", subtitle: "Aman bergaransi" },
                { id: "2", icon: "verified", label: "Kualitas", subtitle: "Grade premium" },
                { id: "3", icon: "support_agent", label: "Konsultasi", subtitle: "Pakar tanaman" },
                { id: "4", icon: "eco", label: "Terawat", subtitle: "Nursery khusus" },
            ],
        },
        catalog_section: {
            heading: "Spesimen",
            highlightText: "Terpilih",
            description: "Varietas eksotis yang telah diseleksi secara ketat dari kebun kami, siap memperkaya koleksi dan ruang Anda.",
            cta: { text: "Eksplorasi Katalog", href: "/product" },
            categories: [
                { id: "all", label: "Semua Koleksi" },
                { id: "monstera", label: "Monstera" },
                { id: "anthurium", label: "Anthurium" },
                { id: "philodendron", label: "Philodendron" },
                { id: "alocasia", label: "Alocasia" },
            ],
        },
        order_process: {
            eyebrow: "Cara Kerja",
            heading: "Transparansi Proses",
            description: "Prosedur pengiriman yang dirancang untuk menjaga kesegaran dan kesehatan tanaman hingga tiba di alamat Anda.",
            steps: [
                { title: "Seleksi Ketat", description: "Pemeriksaan akar dan daun.", icon: "temp_preferences_custom" },
                { title: "Preparasi", description: "Pembersihan media tanam.", icon: "sanitizer" },
                { title: "Pengemasan", description: "Kotak khusus berventilasi.", icon: "inventory_2" },
                { title: "Pengiriman", description: "Logistik terpercaya (1-3 hari).", icon: "local_shipping" },
            ],
        },
        team_section: {
            sectionLabel: "Tim Ahli",
            sectionTitle: "Kurator &",
            sectionTitleHighlight: "Botanikus",
            sectionDescription: "Dipilih dan dirawat oleh tim berpengalaman lebih dari 15 tahun di dunia tanaman hias langka Nusantara.",
            members: [
                { name: "Pak Andi", role: "Spesialis Flora Tropis", bio: "15+ tahun mengidentifikasi mutasi genetik langka dari seluruh Nusantara.", image: "/images/pages/team-1.webp", tags: ["Acquisition", "Tropical"] },
                { name: "Pak Budi", role: "Nursery Manager", bio: "Mengelola 3 hektar nursery di Cipanas dengan standar perawatan premium.", image: "/images/pages/team-2.webp", tags: ["Management", "Quality"] },
                { name: "Pak Hartono", role: "Ahli Konservasi", bio: "Spesialis aklimatisasi tanaman agar optimal sebelum dikirim ke pelanggan.", image: "/images/pages/team-3.webp", tags: ["Care", "Health"] },
                { name: "Bu Sari", role: "Quality Control", bio: "Memastikan setiap tanaman melewati 3 tahap inspeksi sebelum pengiriman.", image: "/images/pages/team-1.webp", tags: ["QC", "Inspection"] },
                { name: "Pak Dimas", role: "Logistics Lead", bio: "Mengatur packaging khusus dan jalur pengiriman ke seluruh Indonesia.", image: "/images/pages/team-2.webp", tags: ["Shipping", "Packaging"] },
                { name: "Bu Ratna", role: "Customer Relations", bio: "Konsultasi perawatan dan pendampingan pasca-pembelian untuk pelanggan.", image: "/images/pages/team-3.webp", tags: ["Support", "Care"] },
            ],
        },
        greenspace_cta: {
            image: "/images/pages/greenspace-cta.webp",
            heading: "Hadirkan Kesegaran Tropis di Ruang Anda",
            description: "Konsultasikan kebutuhan desain interior botani Anda dengan tim ekspertise BMJ.",
            cta: { text: "Konsultasi Gratis", href: "https://wa.me/6281234567890", target: "_blank", bgColor: "brand-dark", icon: "chat" },
        },
        b2b_section: {
            eyebrow: "Layanan Wholesale",
            heading: "Kemitraan B2B",
            description: "Suplai tanaman berskala besar untuk hotel, restoran, ruang kantor, dan proyek desain lanskap.",
            ctaText: "Pelajari B2B",
            ctaHref: "/layanan",
            projectImage: "/images/products/garden-path.webp",
            projectTitle: "Resort Project, Bali",
            projectSubtitle: "Full Landscape Supply",
            services: [
                { title: "Developer Proyek", description: "Suplai tanaman lanskap volume masif.", icon: "corporate_fare" },
                { title: "Desainer Interior", description: "Tanaman spesimen untuk aksen ruang.", icon: "chair" },
                { title: "Kolektor Retail", description: "Varietas langka siap jual.", icon: "storefront" },
                { title: "Pemerintah Daerah", description: "Penghijauan fasilitas publik.", icon: "account_balance" },
            ],
        },
        journal_section: {
            heading: "Jurnal",
            headingHighlight: "Kami",
            ctaLabel: "Baca Semua Artikel",
            ctaHref: "/knowledge",
            articles: [
                { title: "Panduan Variegasi Stabil", category: "Perawatan", image: "/images/products/greenhouse-interior.webp", alt: "Interior greenhouse", excerpt: "Mengapa kelembapan 70% adalah titik ideal untuk Philodendron Anda dan cara mencapainya di dalam ruangan." },
                { title: "Mengidentifikasi Hama Thrips", category: "Hama", image: "/images/products/garden-path.webp", alt: "Garden path", excerpt: "Melihat kondisi ketinggian dan iklim yang membuat spesimen kami tumbuh subur sebelum sampai ke tangan Anda." },
                { title: "Perbanyakan: Moss vs. Perlite", category: "Teknik", image: "/images/products/bonsai-1.webp", alt: "Bonsai collection", excerpt: "Tim ahli hortikultural kami membandingkan substrat terbaik untuk perbanyakan node tanaman." },
            ],
        },
        consultation_cta: {
            headline: "Butuh Saran Spesifik?",
            description: "Tim support kami siap membantu Anda memilih tanaman terbaik sesuai kondisi cahaya dan lingkungan rumah Anda.",
            waNumber: "+62 812-3456-7890",
        },
        excellence_section: {
            eyebrow: "Komitmen Kami",
            heading: "Standar BMJ",
            features: [
                "Lebih dari 500 varietas unik tersedia.",
                "Karantina kesehatan 14 hari sebelum pengiriman.",
                "Garansi hidup 7 hari sejak diterima.",
                "Dukungan purna jual konsultasi gratis selamanya.",
            ],
        },
        testimonials_section: {
            eyebrow: "Testimoni Kolektor",
            heading: "Kepercayaan Pelanggan",
            description: "Bukti komitmen kami pada kualitas dan pelayanan.",
        },
        newsletter_section: {
            heading: "Dapatkan Katalog Terbaru",
            description: "Daftar buletin bulanan kami untuk insight tren tanaman baru eksklusif.",
        },
    },
    navbar: {
        siteName: "Bumi Mekarsari Jaya",
        logoUrl: "",
        links: [
            { label: "Produk", href: "/product", icon: "inventory_2" },
            { label: "Portofolio", href: "/portfolio", icon: "cases" },
            { label: "Layanan", href: "/layanan", icon: "build" },
            { label: "Jurnal", href: "/knowledge", icon: "history_edu" },
            { label: "Tentang", href: "/overview", icon: "info" },
        ],
        loginUrl: "/login",
        registerUrl: "/register",
        navLinkFontSize: "0.8125rem",
        navLinkFontWeight: "600",
        navLinkLetterSpacing: "0.05em",
        navLinkBorderRadius: "4px",
        navLinkPadding: "0.375rem 0.75rem",
        navLinkColor: "#1b3a2d",
        navLinkHoverBg: "#d8d4cd",
        navLinkActiveBg: "#1b3a2d",
        navLinkActiveColor: "#faf9f6",
        ctaBtnWidth: "112px",
        ctaBtnHeight: "40px",
        ctaBtnRadius: "4px",
        ctaBtnFontSize: "16px",
        ctaBtnFontWeight: "400",
        loginBg: "transparent",
        loginColor: "#1a5319",
        loginBorder: "2px solid #1a5319",
        registerBg: "#1a5319",
        registerColor: "#ffffff",
        registerBorder: "none",
    },
    layanan: {
        layanan_hero: {
            heroBadge: "BMJ Supplier & Kelompok Tani",
            heroTitle: "Suplai Tanaman Lanskap & Retail Langsung dari Ratusan Petani Cipanas",
            heroDesc: "Akses tangan pertama ke jaringan petani hias prasejahtera terbesar di Jawa Barat. Harga kompetitif, volume kapasitas besar, dan dukungan pengiriman ke 34 provinsi.",
            heroCtaPrimary: "Konsultasi Kebutuhan",
            heroCtaSecondary: "Download Katalog B2B",
            heroImages: [
                { src: "https://placehold.co/400x500/1F5038/D9A61E?text=Nursery", alt: "Nursery Cipanas" },
                { src: "https://placehold.co/400x500/133D28/AEC9B8?text=Loading", alt: "Proses Loading" },
            ],
        },
        layanan_usp: {
            uspList: [
                { id: "1", title: "Harga Tangan Pertama", desc: "Langsung dari kebun tanpa perantara.", icon: "price_check" },
                { id: "2", title: "Kapasitas Volume", desc: "Mampu suplai >10.000 pohon untuk proyek besar.", icon: "inventory" },
                { id: "3", title: "Standardisasi Kualitas", desc: "Inspeksi ketat sebelum pengiriman.", icon: "verified" },
                { id: "4", title: "Pemberdayaan", desc: "Mendukung ekonomi ratusan petani lokal Cipanas.", icon: "handshake" },
            ],
        },
        layanan_quick_contact: { title: "Butuh Supply Segera?", desc: "Hubungi tim B2B kami untuk negosiasi harga partai besar.", waNumber: "+62 812-3456-7890" },
        layanan_cara_kerja: {
            title: "Proses Kerja B2B",
            desc: "Transparan, profesional, dan dapat diandalkan.",
            steps: [
                { number: "01.", title: "Sourcing", desc: "Kami mencari spesimen sesuai kebutuhan Anda." },
                { number: "02.", title: "Konsolidasi", desc: "Pengumpulan dari berbagai petani mitra di hub kami." },
                { number: "03.", title: "Karantina & QC", desc: "Pembersihan dan pengecekan kesehatan total." },
                { number: "04.", title: "Pengiriman", desc: "Logistik terdedikasi ke seluruh Indonesia." },
            ],
        },
        layanan_partners: {
            title: "Dipercaya Oleh",
            logos: [
                { name: "Agung Sedayu", src: "https://placehold.co/200x80/EEEEEE/999999?text=Partner+1" },
                { name: "Ciputra", src: "https://placehold.co/200x80/EEEEEE/999999?text=Partner+2" },
                { name: "Summarecon", src: "https://placehold.co/200x80/EEEEEE/999999?text=Partner+3" },
                { name: "Pakuwon", src: "https://placehold.co/200x80/EEEEEE/999999?text=Partner+4" },
            ],
        },
        layanan_segmen: {
            title: "Fokus Layanan Kami",
            desc: "Memenuhi kebutuhan beragam klien dari penghobi hingga konglomerasi.",
            segments: [
                { id: "landscape", title: "Suplai Lanskap", desc: "Tanaman peneduh, perdu, dan groundcover dalam partai masif.", icon: "park", features: ["Volume >10.000 pohon", "Jenis tahan banting", "Harga proyek"] },
                { id: "retail", title: "Exotic Retail", desc: "Aroid langka berkualitas kontes untuk kolektor dan toko cabang.", icon: "eco", features: ["Pilihan eksklusif", "Karantina super", "Sertifikat fitosanitari"] },
            ],
        },
        layanan_galeri: {
            title: "Galeri Operasional",
            images: [
                { src: "https://placehold.co/600x400/1F5038/FFFFFF?text=Greenhouse", alt: "Greenhouse", caption: "Kapasitas Ribuan" },
                { src: "https://placehold.co/600x400/1F5038/FFFFFF?text=Quality+Control", alt: "QC", caption: "Inspeksi Akar" },
                { src: "https://placehold.co/600x400/1F5038/FFFFFF?text=Logistics", alt: "Loading", caption: "Packing Profesional" },
            ],
        },
        layanan_pelanggan: {
            title: "Siapa Pelanggan Kami?",
            customers: [
                { id: "1", role: "Developer", desc: "Kebutuhan estetika kawasan" },
                { id: "2", role: "Toko Tanaman", desc: "Suplai barang eksotis konsisten" },
                { id: "3", role: "Pemda", desc: "Penghijauan fasilitas kota" },
            ],
        },
        layanan_logistik: {
            title: "Jangkauan Nasional",
            desc: "Mengirim dengan aman dari ujung Sumatera hingga Papua.",
            mapImage: "https://placehold.co/800x400/133D28/D9A61E?text=Peta+Indonesia",
            coverage: ["Jawa (100% Coverage, Next Day)", "Sumatera (Via Darat/Udara)", "Bali & NTB (Via Darat/Laut)", "Kalimantan & Sulawesi (Via Udara/Pelni)", "Papua (Via Udara Khusus)"],
        },
        layanan_faq: {
            title: "FAQ B2B",
            faqs: [
                { q: "Berapa minimum order untuk harga grosir?", a: "Tergantung jenis tanaman, rata-rata mulai dari 100 pohon atau Rp 5 juta." },
                { q: "Apakah bisa request jenis yang tidak ada di katalog?", a: "Sangat bisa. Hubungi kami, tim sourcer kami akan mencari ke jaringan petani." },
                { q: "Bagaimana sistem pembayaran proyek besar?", a: "Sistem DP 50% di awal, pelunasan 50% setelah barang dimuat ke truk logistik." },
            ],
        },
        layanan_cta: { title: "Mari Berkolaborasi", desc: "Tingkatkan efisiensi dan turunkan HPP proyek Anda dengan mengambil langsung dari petani.", primaryBtn: "WhatsApp Tim Proyek", secondaryBtn: "Email Persyaratan Tender" },
    },
    overview: {
        overview_hero: {
            badge: "Tentang BMJ",
            nibBadge: "NIB: 0712240010385",
            headingPrefix: "PT Bumi Mekarsari Jaya:",
            headingAccent: "Jaringan Supplier",
            headingSuffix: "Tanaman Nusantara",
            trustBadge1: "Legalitas Resmi",
            trustBadge2: "Bibit Unggul",
            heroQuote: '"Mitra Tumbuh Bersama Alam"',
        },
        overview_sticky_nav: {
            items: [
                { id: "statistik", label: "Beranda" },
                { id: "tentang-kami", label: "Overview" },
                { id: "jaringan", label: "Jaringan" },
                { id: "galeri", label: "Galeri" },
                { id: "logistik", label: "Logistik" },
                { id: "kontak", label: "Kontak" },
            ],
        },
        overview_stats: {
            nibText: "NIB: 0712240010385 — Terdaftar di OSS (7 Desember 2024)",
            stats: [
                { value: "1995", label: "Tahun Berdiri", icon: "calendar_month", accent: false },
                { value: "500+", label: "Varietas Tanaman", icon: "potted_plant", accent: false },
                { value: "150+", label: "Petani Mitra", icon: "groups", accent: true },
                { value: "34", label: "Provinsi Diantar", icon: "local_shipping", accent: true },
            ],
        },
        overview_about: { badge: "Tentang BMJ", heading: "Dari Jaringan Petani, untuk Indonesia", stat1Value: "10+", stat1Label: "th Pengalaman", stat2Value: "100%", stat2Label: "Garansi Kualitas" },
        overview_network: { heading: "Sistem Jaringan Terintegrasi", description: "Kami mengelola kualitas dari berbagai titik satelit nursery untuk memastikan ketersediaan stok yang konsisten sepanjang tahun.", centerLabel: "BMJ", centerSubtitle: "Pusat Koordinasi", mitraTitle: "Mitra Unggulan" },
        overview_gallery: {
            badge: "Dokumentasi",
            heading: "Galeri & Dokumentasi",
            tabs: [
                { key: "semua", label: "Semua" },
                { key: "logistik", label: "Logistik" },
                { key: "kebun", label: "Kebun" },
                { key: "proyek", label: "Proyek" },
            ],
            items: [
                { src: "/images/pages/overview-gallery-logistik-1.webp", alt: "Dokumentasi logistik pengiriman tanaman BMJ", category: "logistik", span: "lg:col-span-2 lg:row-span-2" },
                { src: "/images/pages/overview-gallery-logistik-2.webp", alt: "Standar pengemasan tanaman hidup", category: "logistik" },
                { src: "/images/pages/overview-gallery-kebun-1.webp", alt: "Tampak greenhouse nursery mitra BMJ", category: "kebun" },
                { src: "/images/pages/overview-gallery-proyek-1.webp", alt: "Proyek lanskap hotel dengan tanaman dari BMJ", category: "proyek", span: "lg:col-span-2" },
                { src: "/images/pages/overview-gallery-kebun-2.webp", alt: "Area pembibitan tanaman hias di nursery Cipanas", category: "kebun" },
                { src: "/images/pages/overview-gallery-proyek-2.webp", alt: "Proyek taman vertikal perkantoran", category: "proyek" },
            ],
        },
        overview_team: {
            badge: "The Nurserymen",
            heading: "Dipimpin oleh Ahli",
            members: [
                { name: "Dr. Hartono S.", role: "Head Botanist", quote: '"Ilmu tanaman yang baik menghasilkan kualitas yang konsisten."', initials: "HS", bgClass: "from-brand-dark to-brand-deep" },
                { name: "Budi Santoso", role: "Field Coordinator", quote: '"Memberdayakan petani lokal, melayani pasar nasional."', initials: "BS", bgClass: "from-brand-accent/80 to-brand-accent" },
                { name: "Nur Aini", role: "Export Logistics Specialist", quote: '"Ketepatan waktu adalah komitmen, bukan janji."', initials: "NA", bgClass: "from-brand-dark/80 to-brand-dark" },
            ],
        },
        overview_logistics: {
            badge: "Sistem Logistik",
            heading: "Sistem Pengiriman Terintegrasi",
            subtitle: "Dari nursery langsung ke lokasi proyek Anda — dengan jaminan kualitas di setiap tahap.",
            steps: [
                { icon: "inventory_2", title: "Seleksi & Packaging", desc: "Inspeksi kualitas ketat sebelum pengiriman. Packaging khusus tanaman hidup.", step: "01" },
                { icon: "local_shipping", title: "Kurir Darat", desc: "Armada khusus untuk pengiriman antar kota dengan kontrol suhu.", step: "02" },
                { icon: "flight_takeoff", title: "Cargo Udara", desc: "Express delivery via kargo udara untuk pesanan prioritas.", step: "03" },
                { icon: "sailing", title: "Ekspedisi Laut", desc: "Pengiriman kontainer untuk volume besar antar pulau.", step: "04" },
            ],
            partnersLabel: "Mitra Ekspedisi",
            partners: ["JNE", "J&T", "SiCepat", "POS Indonesia", "DHL", "TIKI"],
        },
        overview_guarantee: { heading: "Garansi 100% Aman", description: "Kami menjamin setiap tanaman tiba dalam kondisi prima. Jika terjadi kerusakan saat pengiriman, kami akan mengganti dengan unit baru atau melakukan refund — tanpa syarat rumit.", badgeText: "Terproteksi" },
        overview_testimonials: {
            badge: "Testimoni",
            heading: "Dipercaya Mitra Bisnis",
            testimonials: [
                { name: "Ahmad Hidayat", company: "PT Green Landscape Indonesia", rating: 5, content: "Kualitas tanaman dari BMJ sangat konsisten. Pengiriman ke proyek resort di Bali pun tiba dalam kondisi prima. Sudah 3 tahun jadi partner B2B kami.", initials: "AH" },
                { name: "Dewi Lestari", company: "Interior Design Studio Bali", rating: 5, content: "Varietas monstera dan philodendron dari jaringan BMJ sangat lengkap. Support tim untuk konsultasi jenis tanaman indoor sangat membantu.", initials: "DL" },
                { name: "Budi Santoso", company: "Developer Property Jakarta", rating: 5, content: "Proyek landscaping 3 cluster perumahan kami ditangani dengan baik. Kapasitas supply besar jadi keunggulan utama BMJ.", initials: "BS" },
            ],
        },
        overview_faq: { badge: "FAQ", heading: "Pertanyaan Umum", subtitle: "Jawaban untuk pertanyaan yang sering ditanyakan oleh mitra bisnis kami." },
        overview_contact: { badge: "Hubungi Kami", heading: "Mulai Konsultasi", subtitle: "Tim kami siap membantu kebutuhan tanaman untuk proyek Anda." },
    },
    "knowledge-page": {
        knowledge_hero: { badge: "BMJ Knowledge Base", title: "The Botanical Archive", description: "Database komprehensif perawatan tanaman tropis, identifikasi spesies, dan panduan kultivasi dari tim ahli BMJ Nursery.", authorName: "Dr. Hartono & BMJ Expert Team", authorRole: "Head Botanist" },
        knowledge_category_nav: {
            title: "Jelajahi Kategori",
            categories: [
                { id: "panduan-dasar", title: "Panduan Dasar", icon: "menu_book", count: 24, path: "/knowledge/category/panduan-dasar" },
                { id: "perawatan", title: "Perawatan", icon: "water_drop", count: 86, path: "/knowledge/category/perawatan" },
                { id: "identifikasi", title: "Identifikasi", icon: "search", count: 112, path: "/knowledge/category/identifikasi" },
                { id: "hama-penyakit", title: "Hama & Penyakit", icon: "bug_report", count: 45, path: "/knowledge/category/hama-penyakit" },
                { id: "kultur-jaringan", title: "Kultur Jaringan", icon: "biotech", count: 18, path: "/knowledge/category/kultur-jaringan" },
            ],
        },
        knowledge_featured: { badge: "Feature Article", title: "Panduan Identifikasi Hybrid Philodendron", description: "Pelajari cara membedakan hybrid Philodendron kompleks melalui analisis morfologi daun, bentuk batang, dan warna cataphyll.", author: "Tim Ahli Botani", date: "14 Aug 2024", readTime: "8 min read", image: "/images/knowledge/knowledge-featured-philodendron.webp", slug: "panduan-identifikasi-hybrid-philodendron", category: "Identifikasi Spesies" },
        knowledge_zone_mengenal: { sectionNumber: "01.", sectionTitle: "Mengenal", sectionSubtitle: "Classification", featuredImage: "/images/knowledge/knowledge-mengenal-botany.webp", featuredImageAlt: "Taksonomi Araceae", featuredBadge: "Featured", featuredTitle: "Taksonomi Araceae", featuredDesc: "Dasar klasifikasi botani untuk identifikasi akurat famili Araceae.", featuredAuthor: "Dr. Hartono", subLinks: [{ icon: "psychology", title: "Morfologi Daun & Venasi" }, { icon: "forest", title: "Habitat Hutan Tropis" }] },
        knowledge_zone_memilih: { sectionNumber: "02.", sectionTitle: "Memilih", sectionSubtitle: "Selection", featuredImage: "/images/knowledge/knowledge-memilih-selection.webp", featuredImageAlt: "Inspeksi Kesehatan", featuredBadge: "Essential Guide", featuredTitle: "Panduan Inspeksi Kesehatan Tanaman", featuredDesc: "Panduan visual mendeteksi penyakit dan memilih spesimen berkualitas.", desktopSubLinks: ["Memilih Pot yang Tepat", "Variegata vs Non-Variegata"], mobileHeroTitle: "Inspeksi Kesehatan", mobileHeroDesc: "Panduan visual mendeteksi penyakit.", mobileSubArticles: [{ title: "Teknik Menjaga Variegasi Stabil", subtitle: "Monstera Guide", img: "/images/knowledge/knowledge-monstera.webp" }, { title: "Cutting vs Tanaman Utuh", subtitle: "Investasi Cerdas", img: "/images/knowledge/knowledge-cutting.webp" }] },
        knowledge_zone_merawat: { sectionNumber: "03.", sectionTitle: "Merawat", sectionSubtitle: "Care Database", mobileSubtitle: "The Care Dashboard", careCategories: [{ icon: "water_drop", title: "Water", subtitle: "Teknik Penyiraman", count: 12 }, { icon: "wb_sunny", title: "Light", subtitle: "Kebutuhan Cahaya", count: 8 }, { icon: "science", title: "Soil", subtitle: "Nutrisi & Pupuk", count: 15 }, { icon: "bug_report", title: "Pests", subtitle: "Hama & Penyakit", count: 6 }] },
        knowledge_zone_menggunakan: { sectionNumber: "04.", sectionTitle: "Menggunakan", sectionSubtitle: "Design & Decor", articles: [{ category: "Interior Styling", title: "Ruang Minim Cahaya", description: "Solusi estetis untuk sudut gelap.", img: "/images/knowledge/knowledge-interior.webp", alt: "Interior" }, { category: "Landscape Arch", title: "Tropical Garden Modern", description: "Elemen hardscape minimalis.", img: "/images/knowledge/knowledge-landscape.webp", alt: "Landscape" }] },
        knowledge_editorial: { badge: "Pusat Otoritas Botani", title: "Tim Riset & Ahli Hortikultura", description: "Integritas botani adalah janji kami. Setiap panduan dirumuskan berdasarkan data lapang dari Nursery Cipanas dan literatur divalidasi oleh dewan ahli kami.", image: "/images/knowledge/knowledge-editorial-team.webp", quoteText: "Kualitas tanaman tidak hanya diukur saat ia tiba, tetapi pada bagaimana ia bertahan dan beradaptasi.", quoteAuthor: "— Dr. Hartono S.", disclaimerTitle: "General Guidance", disclaimerText: "Disclaimer: Informasi yang disajikan bersifat umum dan edukatif. Untuk kondisi spesifik tanaman Anda, konsultasikan langsung dengan tim ahli kami." },
        knowledge_tren: { sectionNumber: "05.", sectionTitle: "Tren & Updates", loadMoreText: "Muat Lebih Banyak", articles: [{ category: "Market Report", title: "Anthurium Papillilaminum Hybrid Market 2024", description: "Analisis harga dan permintaan pasar global.", img: "/images/knowledge/knowledge-trend1.webp", date: "12 Aug", readTime: "5 Min" }, { category: "Tips", title: "Manajemen Dormansi Alocasia", description: "Strategi pencahayaan buatan.", img: "/images/knowledge/knowledge-trend2.webp", date: "10 Aug", readTime: "4 Min" }, { category: "Research", title: "Philodendron Gloriosum vs Melanochrysum", description: "Perbandingan mendalam.", img: "/images/knowledge/knowledge-trend3.webp", date: "8 Aug", readTime: "7 Min" }, { category: "Industry", title: "Sertifikasi CITES untuk Ekspor", description: "Panduan kelengkapan dokumen.", img: "/images/knowledge/knowledge-trend4.webp", date: "5 Aug", readTime: "6 Min" }] },
    },
    "portfolio-page": {
        portfolio_hero: {
            title: "Kelompok Tani & Supplier Tanaman Hias Nasional",
            subtitle: "Dari Hub Cipanas untuk Seluruh Indonesia",
            description: "BMJ mengkoordinasikan ratusan petani tanaman hias di Cipanas — pusat industri tanaman hias terbesar di Indonesia. Kapasitas supply besar melalui aggregasi jaringan petani berpengalaman.",
            backgroundImage: "/images/portfolio/portfolio-hero.webp",
            stats: [
                { value: "100+", label: "Petani Mitra", icon: "groups" },
                { value: "10K+", label: "Kapasitas Pohon/Order", icon: "forest" },
                { value: "34", label: "Provinsi Terjangkau", icon: "local_shipping" },
            ],
        },
        portfolio_services: {
            services: [
                { icon: "park", title: "Suplai Proyek Lanskap", description: "Tanaman groundcover, perdu, peneduh, dan palem untuk proyek properti, hotel, taman kota. Minimum order 10.000 pohon.", tag: "B2B • Skala Besar" },
                { icon: "local_florist", title: "Tanaman Exotic & Koleksi", description: "Monstera, Philodendron, Anthurium, Aglonema dan varietas langka untuk kolektor dan retailer.", tag: "B2B + B2C" },
                { icon: "handshake", title: "Koordinasi Petani", description: "Sebagai kelompok tani, BMJ menghubungkan ratusan petani di Cipanas dengan buyer nasional dan internasional.", tag: "Farmer Cooperative" },
            ],
        },
        portfolio_segments: {
            title: "Dua Segmen, Satu Ekosistem",
            items: [
                { label: "Tanaman Proyek", description: "Landscape supply untuk developer, kontraktor, dan pemerintah", icon: "apartment", percentage: "50%", examples: ["Groundcover & rumput", "Perdu & semak hias", "Tanaman peneduh", "Palem & tanaman border", "Vertical garden"] },
                { label: "Tanaman Exotic", description: "Varietas koleksi untuk kolektor, retailer, dan hobbyist", icon: "eco", percentage: "50%", examples: ["Monstera (Albo, Thai Con)", "Philodendron langka", "Anthurium premium", "Aglonema mutasi", "Aroid koleksi lainnya"] },
            ],
        },
        portfolio_projects: {
            badge: "Galeri Proyek",
            heading: "Proyek & Koleksi Terbaru",
            projects: [
                { slug: "project-1", image: "/images/portfolio/portfolio-project-1.webp", imageAlt: "Proyek Lanskap Hotel Bali", title: "Proyek Lanskap Hotel", category: "Lanskap", location: "Bali", scale: "Besar" },
                { slug: "project-2", image: "/images/portfolio/portfolio-project-2.webp", imageAlt: "Koleksi Monstera Langka", title: "Koleksi Monstera Langka", category: "Eksotik", location: "Jakarta", scale: "Kolektor" },
                { slug: "project-3", image: "/images/portfolio/delivery-loading.webp", imageAlt: "Dokumentasi Pengiriman Cipanas-Surabaya", title: "Dokumentasi Pengiriman", category: "Logistik", location: "Cipanas → Surabaya", scale: "500 Tanaman" },
            ],
        },
        portfolio_logistics: {
            title: "Jangkauan Pengiriman",
            subtitle: "Nasional & Internasional",
            islands: [{ name: "Jawa", active: true }, { name: "Sumatera", active: true }, { name: "Kalimantan", active: true }, { name: "Sulawesi", active: true }, { name: "Bali & NTB", active: true }, { name: "Papua", active: true }],
            destinations: [{ city: "Jakarta" }, { city: "Surabaya" }, { city: "Bandung" }, { city: "Denpasar" }, { city: "Medan" }, { city: "Makassar" }, { city: "Yogyakarta" }, { city: "Semarang" }],
            shippingNote: "Pengiriman menggunakan jasa logistik pihak ketiga terpercaya. Ekspor internasional tersedia dengan frekuensi terbatas.",
        },
        portfolio_process_cta: {
            processTitle: "Proses Kerja",
            steps: [
                { number: "01", title: "Konsultasi", description: "Diskusi kebutuhan proyek, jenis tanaman, volume, dan timeline", icon: "chat" },
                { number: "02", title: "Seleksi & Koordinasi", description: "Koordinasi dengan petani mitra untuk sourcing tanaman sesuai spesifikasi", icon: "checklist" },
                { number: "03", title: "Quality Control", description: "Inspeksi kualitas di kebun sebelum pengiriman", icon: "verified" },
                { number: "04", title: "Pengiriman", description: "Packing profesional dan pengiriman via logistik pihak ketiga terpercaya", icon: "local_shipping" },
            ],
            ctaTitle: "Siap untuk Proyek Anda?",
            ctaSubtitle: "Konsultasi gratis untuk kebutuhan tanaman proyek lanskap atau koleksi exotic. Kami siap supply dari ratusan petani mitra di Cipanas.",
            primaryLabel: "Konsultasi via WhatsApp",
            secondaryLabel: "Lihat Katalog Tanaman",
        },
    },
};
